
import { Customer, CustomerStatus } from './types';

const mapDate = (seconds: number) => new Date(seconds * 1000).toLocaleDateString('pt-BR');

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "12hFto58m0LrWa3J55W9",
    name: "Ana Paula Almeida da Silva",
    email: "",
    cpf: "481.068.858-52",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765333271),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/12hFto58m0LrWa3J55W9/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "5nPHBRUWEWrudXswCxF8",
    name: "Paola Clair da Silva",
    email: "",
    cpf: "291.178.818-46",
    phone: "11) 9 1485-4372",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765752476),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/5nPHBRUWEWrudXswCxF8/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "6fxZOZoDqLYzxPfuQa58",
    name: "Fernanda lopes da costa",
    email: "",
    cpf: "37895067885",
    phone: "11967753738",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765763084),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/6fxZOZoDqLYzxPfuQa58/200",
    address: { 
      cep: "04777110", 
      street: "Rua João Bertacchi", 
      number: "101", 
      bairro: "Jardim Cristal", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "6gzasMqUWHBr2rlTxiwO",
    name: "ALESSANDRO ZANELLI",
    email: "",
    cpf: "",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765763637),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/6gzasMqUWHBr2rlTxiwO/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "89lYnFwdH7T0gMcW4zUE",
    name: "Angelo Lovaglio",
    email: "",
    cpf: "006.575.598-73",
    phone: "55(11) 9 1760-506",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765334973),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/89lYnFwdH7T0gMcW4zUE/200",
    address: { cep: "", street: "Rua Jaime Rodrigues", number: "398", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "8jNy3UukBs1tcWh0Dqh9",
    name: "Nildo El Patron",
    email: "",
    cpf: "",
    phone: "(11)9 6 7240-648",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765751001),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/8jNy3UukBs1tcWh0Dqh9/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "8mADHALF9N0QKkxzxW8b",
    name: "Lucas Tadeu Ramos de Brito",
    email: "",
    cpf: "",
    phone: "(11) 999 6300-62",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765745522),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/8mADHALF9N0QKkxzxW8b/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "8mdlIsSAx4be5zrC5anK",
    name: "Rosilda Pereira da Silva",
    email: "",
    cpf: "061.093.268-38",
    phone: "(11) 98 8905-426",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765757119),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/8mdlIsSAx4be5zrC5anK/200",
    address: { 
      cep: "03350-005", 
      street: "Rua Doutor Gabriel de Resende", 
      number: "28", 
      bairro: "Vila Invernada", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "9rkCouQ9GZysuHvj0QNG",
    name: "Elisangela do Nascimento Souza Luciano",
    email: "",
    cpf: "118.702.567",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765338480),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/9rkCouQ9GZysuHvj0QNG/200",
    address: { 
      cep: "", 
      street: "Rua Maria Moura de Melo Silva", 
      number: "83", 
      bairro: "", 
      city: "", 
      state: "" 
    },
    installments: [],
    documents: []
  },
  {
    id: "BporUWGk2EsDjSi5c2u8",
    name: "ADAUTO RAMOS DA SILVA",
    email: "",
    cpf: "17692233802",
    phone: "11974230606",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765330770),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/BporUWGk2EsDjSi5c2u8/200",
    address: { 
      cep: "04436040", 
      street: "Rua Plácido Nunes Vieira", 
      number: "102", 
      bairro: "Jardim Consórcio", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "CGD2Bytyuqg8FIE3mGmG",
    name: "ALESSANDRO ZANELLI",
    email: "",
    cpf: "",
    phone: "11970518210",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765331334),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/CGD2Bytyuqg8FIE3mGmG/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "Cjq58fUQn4OlewhFY0x7",
    name: "Sheila Oliveira Santos",
    email: "",
    cpf: "286.641.498-52",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765760674),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Cjq58fUQn4OlewhFY0x7/200",
    address: { 
      cep: "04455-180", 
      street: "Rua Sargento Olício Alves", 
      number: "", 
      bairro: "Vila Campo Grande", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "CwW0bUl3cuWWbd8RHC4P",
    name: "Estela Zadroczynski de Carvalho",
    email: "",
    cpf: "145.189.548-82",
    phone: "55(11)9 7 7005-962",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765338880),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/CwW0bUl3cuWWbd8RHC4P/200",
    address: { 
      cep: "06283-000", 
      street: "Rua Antônio de Campos Toledo", 
      number: "451", 
      bairro: "Ayrosa", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "E2d2qDLSZi9anQrReMgz",
    name: "Tylla Amaratti Leão ",
    email: "",
    cpf: "",
    phone: "+55 11 94076-8707",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1767039892),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/E2d2qDLSZi9anQrReMgz/200",
    address: { cep: "", street: "Scipião ", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "FpurzMRzwOWEHutG2n1R",
    name: "Silvio Cesar de carvalho",
    email: "",
    cpf: "09960527808",
    phone: "11932119169",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766000938),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/FpurzMRzwOWEHutG2n1R/200",
    address: { 
      cep: "06283000", 
      street: "Rua Antônio de Campos Toledo", 
      number: "541", 
      bairro: "Ayrosa", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "GXb1snLDl48gKY3gcL3o",
    name: "Karina Lima dos Santos",
    email: "",
    cpf: "532.462.548-50",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765344557),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/GXb1snLDl48gKY3gcL3o/200",
    address: { 
      cep: "08270-070", 
      street: "Rua Santa Marcelina", 
      number: "785", 
      bairro: "Vila Carmosina", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "HNuPfidQGVABB6l7GZoh",
    name: "Lindalva Mourao dos Santos Lima ",
    email: "",
    cpf: "56411952353",
    phone: "11955956716",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1767123496),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/HNuPfidQGVABB6l7GZoh/200",
    address: { 
      cep: "02734010", 
      street: "Rua Quito", 
      number: "116", 
      bairro: "Nossa Senhora do Ó", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "IYTAdUs0sNQtvOlEcby8",
    name: "Mariana Santos Cardoso",
    email: "",
    cpf: "402.681.658-31",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765749108),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/IYTAdUs0sNQtvOlEcby8/200",
    address: { cep: "11) 9 1760-506", street: "", number: "95", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "J41muomY5ZIozHrxsy1o",
    name: "Rosecleia de Almeida",
    email: "",
    cpf: "161.157.268-16",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765756528),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/J41muomY5ZIozHrxsy1o/200",
    address: { 
      cep: "06390-180", 
      street: "Estrada Jathay", 
      number: "235", 
      bairro: "Vila Nossa Senhora Aparecida", 
      city: "Carapicuíba", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "JkG7KbuLWaqUVE1Y0c3q",
    name: "Silvana Bertoloni Lima",
    email: "",
    cpf: "",
    phone: "11999777597",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766016593),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/JkG7KbuLWaqUVE1Y0c3q/200",
    address: { 
      cep: "02082030", 
      street: "Rua Quedas", 
      number: "472", 
      bairro: "Vila Isolina Mazzei", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "KUzMWcNL3bZN8N5TvFQs",
    name: "Felipe Garcia Rossini",
    email: "",
    cpf: "418.461.658-57",
    phone: "(11) 9 1003-5062",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765767130),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/KUzMWcNL3bZN8N5TvFQs/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "Ld83hYwKzHnUMULoGAGt",
    name: "Renato Antônio da Anunciação",
    email: "",
    cpf: "361.483.868-44",
    phone: "(11) 9 1449-254",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765755284),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Ld83hYwKzHnUMULoGAGt/200",
    address: { 
      cep: "06462-040", 
      street: "Rua Tomé de Souza", 
      number: "06", 
      bairro: "Parque Imperial", 
      city: "Barueri", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "MbSzIDUsLE37vYKQwHk1",
    name: "Samira Santos Torre Chaves",
    email: "",
    cpf: "355.085.008-55",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765760362),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/MbSzIDUsLE37vYKQwHk1/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "MujqFlnQWS9JDMeDUBh3",
    name: "Fabiana Cardoso de Souza Lopes",
    email: "",
    cpf: "428.105.798-65",
    phone: "+55 11 95339-0673",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765339205),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/MujqFlnQWS9JDMeDUBh3/200",
    address: { 
      cep: "02836-000", 
      street: "Rua Domingos Francisco Lisboa", 
      number: "116", 
      bairro: "Vila Serralheiro", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "NKtaOLZyc0u6dVUlQ8Ew",
    name: "Rosângela Eudoxia Barbosa",
    email: "",
    cpf: "140.829.378-11",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765757972),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/NKtaOLZyc0u6dVUlQ8Ew/200",
    address: { 
      cep: "06142-055", 
      street: "Rua Maria Moura de Melo Silva", 
      number: "23", 
      bairro: "Novo Osasco", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Nu2NgrYtguwFGOFGg6LK",
    name: "Patrícia Oliveira Pereira",
    email: "",
    cpf: "350.336.988-00",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765752993),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Nu2NgrYtguwFGOFGg6LK/200",
    address: { 
      cep: "06216-310", 
      street: "Rua Ida Madeira Caputo", 
      number: "98", 
      bairro: "Presidente Altino", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "PHauBCaPx0AcXYf6PUEa",
    name: "Vanessa Melsohn",
    email: "",
    cpf: "01233-000",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765761645),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/PHauBCaPx0AcXYf6PUEa/200",
    address: { 
      cep: "01233-000", 
      street: "Rua Tupi", 
      number: "496", 
      bairro: "Santa Cecília", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "QDCijqPKmTIgSGCPbQzP",
    name: "Viviane Aparecida da Silva",
    email: "",
    cpf: "386.422.078-50",
    phone: "(11)9 8 1584-731",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765762689),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/QDCijqPKmTIgSGCPbQzP/200",
    address: { 
      cep: "08235-850", 
      street: "Rua Lacre", 
      number: "80", 
      bairro: "Parque Guarani", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Ri3xW8YKc19Mq0OviMcR",
    name: "Maria Amélia de Souza de Almeida",
    email: "",
    cpf: "110.834.808-47",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765747504),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Ri3xW8YKc19Mq0OviMcR/200",
    address: { 
      cep: "06807-375", 
      street: "Rua Manaus", 
      number: "18", 
      bairro: "Jardim Vista Alegre", 
      city: "Embu das Artes", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Rj79q2y80WKn5wlGJ8el",
    name: "Samira Hidalgo do Nascimento",
    email: "",
    cpf: "1.591.424-41",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765759895),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Rj79q2y80WKn5wlGJ8el/200",
    address: { 
      cep: "05012-010", 
      street: "Rua Ministro Gastão Mesquita", 
      number: "767", 
      bairro: "Perdizes", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Ru7E74QSED1BpcRyUUlg",
    name: "Roanita da Silva Lima ",
    email: "",
    cpf: "330.323.458-20",
    phone: "+55 11 95657-8462",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766092844),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Ru7E74QSED1BpcRyUUlg/200",
    address: { 
      cep: "06871170", 
      street: "Rua Sílvio Ferreira Domingues", 
      number: "121", 
      bairro: "Jardim das Palmeiras", 
      city: "Itapecerica da Serra", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Snli9hTDMg7NOGaR5Qly",
    name: "Ana Carolina Barbosa de Souza Alves",
    email: "",
    cpf: "45356373856",
    phone: "+55 11 99245-6732",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766508995),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Snli9hTDMg7NOGaR5Qly/200",
    address: { 
      cep: "04045000", 
      street: "Avenida Jabaquara", 
      number: "3850", 
      bairro: "Mirandópolis", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "UcSbhbNSCOnfDqWf1Uoq",
    name: "Michelle Pereira dos Santos",
    email: "",
    cpf: "",
    phone: "(11) 9 9766-271",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765750799),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/UcSbhbNSCOnfDqWf1Uoq/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "W7tMg7zYi1O8tbqUwlNr",
    name: "Maria Célia Diniz da Anunciação",
    email: "",
    cpf: "170.512.188-83",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765332960),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/W7tMg7zYi1O8tbqUwlNr/200",
    address: { 
      cep: "06462-040", 
      street: "Rua Tomé de Souza", 
      number: "06", 
      bairro: "Parque Imperial", 
      city: "Barueri", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "WRlqF7lzbGHUWULQt5ua",
    name: "Helenildo Gonçalves dos Santos",
    email: "",
    cpf: "",
    phone: "+5511963469248",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765764039),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/WRlqF7lzbGHUWULQt5ua/200",
    address: { 
      cep: "04446-230", 
      street: "Rua Jaime Rodrigues", 
      number: "305", 
      bairro: "Jardim Sabará", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "X237xknCtOCYxiJyRwWL",
    name: "Joselito Batista dos Santos ",
    email: "",
    cpf: "81127774891",
    phone: "+55 11 97493-6401",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766094296),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/X237xknCtOCYxiJyRwWL/200",
    address: { 
      cep: "02834030", 
      street: "Rua João Daudt Filho", 
      number: "131", 
      bairro: "Vila Nina", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "XAqK2RYwKHg9UFFVQUuR",
    name: "Maria das Dores Santana de Souza Silva",
    email: "",
    cpf: "922.709.723-08",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765747990),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/XAqK2RYwKHg9UFFVQUuR/200",
    address: { 
      cep: "06462-210", 
      street: "Rua di Cavalcanti", 
      number: "116", 
      bairro: "Parque Imperial", 
      city: "Barueri", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "Y6vstCNhxPF4yAlyJ7EC",
    name: "Douglas Aparecido ferreira Jacob",
    email: "",
    cpf: "50957110871",
    phone: "+55 11 99761-1677",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766510445),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/Y6vstCNhxPF4yAlyJ7EC/200",
    address: { 
      cep: "06817040", 
      street: "Rua das Rosas", 
      number: "98", 
      bairro: "Jardim Lavorato", 
      city: "Embu das Artes", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "YGVVQmkhSyPz94E8pTrE",
    name: "Rita de Cassia de Almeida Rahal",
    email: "",
    cpf: "043.795.578-80",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765755971),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/YGVVQmkhSyPz94E8pTrE/200",
    address: { 
      cep: "05592-070", 
      street: "Rua Capitão Nicolau Puccini", 
      number: "77", 
      bairro: "Jardim Bonfiglioli", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "YOWD17gA03hfMv8LPC9R",
    name: "Tylla Amaratti Leão ",
    email: "",
    cpf: "",
    phone: "+55 11 94076-8707",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1767039888),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/YOWD17gA03hfMv8LPC9R/200",
    address: { cep: "", street: "Scipião ", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "YmUBkHC6JYBEoWIzYrxq",
    name: "Luciane Fioratti",
    email: "",
    cpf: "259.182.488-62",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765745866),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/YmUBkHC6JYBEoWIzYrxq/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "bClXIJmuwxGAdQmaQd0e",
    name: "Rafael Antônio da Anunciacao",
    email: "",
    cpf: "466.841.938-98",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765753833),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/bClXIJmuwxGAdQmaQd0e/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "c1BgqqzLoQm6i1pGxB31",
    name: "Ednei Elpatron",
    email: "",
    cpf: "986.669.915-34",
    phone: "(11) 9 5924-8926",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765766645),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/c1BgqqzLoQm6i1pGxB31/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "cnAzH9FDY9KgF8iyB2jr",
    name: "Israel Nicolau lima",
    email: "",
    cpf: "047.453.868-00",
    phone: "55(11)9 6 7530-197",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765343892),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/cnAzH9FDY9KgF8iyB2jr/200",
    address: { 
      cep: "04185-050", 
      street: "Rua José Cezário Coelho", 
      number: "15", 
      bairro: "Vila Liviero", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "enwli2HL4iEBNF40YG7j",
    name: "Estela Zadroczynski de Carvalho",
    email: "",
    cpf: "",
    phone: "+5511977005962",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765743623),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/enwli2HL4iEBNF40YG7j/200",
    address: { 
      cep: "06283-000", 
      street: "Rua Antônio de Campos Toledo", 
      number: "451", 
      bairro: "Ayrosa", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "fPbSl86Vktonk5xDAOkd",
    name: "TAGLIANE GOMES DA SILVA",
    email: "",
    cpf: "44475485851",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765345425),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/fPbSl86Vktonk5xDAOkd/200",
    address: { 
      cep: "06436140", 
      street: "Rua Glória", 
      number: "133", 
      bairro: "Parque dos Camargos", 
      city: "Barueri", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "gRxwiBqHBrpXN1dWC6Io",
    name: "Samira Hidalgo do Nascimento",
    email: "",
    cpf: "",
    phone: "1196337458",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766262305),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/gRxwiBqHBrpXN1dWC6Io/200",
    address: { 
      cep: "05012-010", 
      street: "Rua Ministro Gastão Mesquita", 
      number: "767", 
      bairro: "Perdizes", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "gpRo8dbjaVoEPkKudEqD",
    name: "Bar restaurante e pizzaria teos bets",
    email: "",
    cpf: "30107994895",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765335324),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/gpRo8dbjaVoEPkKudEqD/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "guY5g31FcnAZFqwXhoSS",
    name: "Graciete Fonceca",
    email: "",
    cpf: "677.207.575-72",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765342805),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/guY5g31FcnAZFqwXhoSS/200",
    address: { 
      cep: "04455-240", 
      street: "Rua Ernesto Rothschild", 
      number: "106", 
      bairro: "Vila Campo Grande", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "gyd1ONJ845UwDHnOYYXd",
    name: "Paulo André Puhl",
    email: "",
    cpf: "66974585004",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765769849),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/gyd1ONJ845UwDHnOYYXd/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "hokJum6ozz0PlZ1ein4x",
    name: "Luiz Marcelo Maia de Freitas",
    email: "",
    cpf: "237.683.028-14",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765747004),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/hokJum6ozz0PlZ1ein4x/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "idscVil0NXpomeVYeiQH",
    name: "Francisca Neudima ",
    email: "",
    cpf: "",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766604545),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/idscVil0NXpomeVYeiQH/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "ipyLHFXM2ZqxEEg91xno",
    name: "Urus MG",
    email: "",
    cpf: "",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765835936),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/ipyLHFXM2ZqxEEg91xno/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "iqxWvog2ewsqNtvJAPSS",
    name: "TROCA VR",
    email: "",
    cpf: "",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766452487),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/iqxWvog2ewsqNtvJAPSS/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "lZEOgL64bUN0sgdj82Wt",
    name: "Anamelia Galbossera",
    email: "",
    cpf: "083.963.608-39",
    phone: "55(11)9 4 4668-573",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765333709),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/lZEOgL64bUN0sgdj82Wt/200",
    address: { 
      cep: "05021-001", 
      street: "Rua Cotoxó", 
      number: "839", 
      bairro: "Perdizes", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "mcXM2FoPkLCa2axVlncO",
    name: "AMANDA CARINA GOMES",
    email: "",
    cpf: "50709043880",
    phone: "11978487442",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765332258),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/mcXM2FoPkLCa2axVlncO/200",
    address: { 
      cep: "06142290", 
      street: "Rua José Yoshie Yamamoto", 
      number: "", 
      bairro: "Novo Osasco", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "nWZpJweppSgfd0D78rvk",
    name: "Luciane Alves de Santana Ferreira",
    email: "",
    cpf: "079.373.278-63",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765746432),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/nWZpJweppSgfd0D78rvk/200",
    address: { 
      cep: "06170-018", 
      street: "Rua José Henrique de Lima", 
      number: "29 antigo 74", 
      bairro: "Jardim Roberto", 
      city: "Osasco", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "oqkSnCEdRz8yqKwst3yZ",
    name: "Carlos Alberto de Freitas",
    email: "",
    cpf: "153.665.248-22",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765337409),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/oqkSnCEdRz8yqKwst3yZ/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "qpcSxtOLBH3xnojxNK2o",
    name: "Jean Carlos Cantor ",
    email: "",
    cpf: "",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1766604234),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/qpcSxtOLBH3xnojxNK2o/200",
    address: { cep: "", street: "", number: "", bairro: "", city: "", state: "" },
    installments: [],
    documents: []
  },
  {
    id: "sVYuo0AbqgxPvTqef2rz",
    name: "Gabriel Iago Clair de Almeida",
    email: "",
    cpf: "",
    phone: "+5511946711041",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765821600),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/sVYuo0AbqgxPvTqef2rz/200",
    address: { 
      cep: "05102-090", 
      street: "Rua Domingos de Braga", 
      number: "157", 
      bairro: "Vila dos Remédios", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "ts26eJrOJs5JTrqxHqbp",
    name: "Vitoria Heloísa Elias Sousa",
    email: "",
    cpf: "510.244.248-12",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765762066),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/ts26eJrOJs5JTrqxHqbp/200",
    address: { 
      cep: "02129-060", 
      street: "Rua Porangatu", 
      number: "291", 
      bairro: "Vila Maria Alta", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "x0Z2qv83B4TlRDiadOWH",
    name: "Regina da Silva Gomes",
    email: "",
    cpf: "634.661.985-34",
    phone: "(11) 91 5947-020",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765754247),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/x0Z2qv83B4TlRDiadOWH/200",
    address: { 
      cep: "02726-090", 
      street: "Rua Bartholomeu do Canto", 
      number: "286", 
      bairro: "Vila Palmeiras", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "xJQlFISnwHBsLpkyOCQq",
    name: "Angela Cristina Julião Pinheiro",
    email: "",
    cpf: "117.563.728-96",
    phone: "55(11)9 7 6282-167",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765334357),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/xJQlFISnwHBsLpkyOCQq/200",
    address: { 
      cep: "02423-090", 
      street: "Rua Pinhal Alto", 
      number: "160", 
      bairro: "Jardim Carlu", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "xtcnUFycsqCdpHZTaaOi",
    name: "Olga Virgínia Fonseca do Nascimento",
    email: "",
    cpf: "921.910.708-25",
    phone: "+55 16 99220-2077",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765751477),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/xtcnUFycsqCdpHZTaaOi/200",
    address: { 
      cep: "01244-020", 
      street: "Rua Novo Horizonte", 
      number: "159", 
      bairro: "Higienópolis", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  },
  {
    id: "y83TM7xUEegrKJLYB9pN",
    name: "Fernandes Augusto de Mendonca junior",
    email: "",
    cpf: "354.744.098-00",
    phone: "",
    status: CustomerStatus.ACTIVE,
    joinedDate: mapDate(1765339908),
    totalLoaned: 0,
    balanceDue: 0,
    avatar: "https://picsum.photos/seed/y83TM7xUEegrKJLYB9pN/200",
    address: { 
      cep: "03578-180", 
      street: "Rua Cairê", 
      number: "121", 
      bairro: "Jardim Eliane", 
      city: "São Paulo", 
      state: "SP" 
    },
    installments: [],
    documents: []
  }
];

export const MOCK_TRANSACTIONS: any[] = [];
